tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"

brew "autojump"
brew "bat"
brew "buildkit"
brew "coreutils"
brew "d2"
brew "direnv"
brew "elixir"
brew "ffmpeg"
brew "git-crypt"
brew "gitup"
brew "go"
brew "httpie"
brew "mas"
brew "pre-commit"
brew "pure"
brew "python@3.10"
brew "restic"
brew "tldr"
brew "vdirsyncer"
brew "wget"
brew "zsh-completions"

cask "autodesk-fusion360"
cask "beekeeper-studio"
cask "bruno"
cask "elmedia-player"
cask "firefox"
cask "font-jetbrains-mono"
cask "karabiner-elements"
cask "keepassxc"
cask "livebook"
cask "messenger"
cask "monitorcontrol"
cask "mos"
cask "obsidian"
cask "onyx"
cask "orbstack"
cask "platypus"
cask "postgres-unofficial"
cask "proxy-audio-device"
cask "prusaslicer"
cask "qnapi"
cask "rectangle-pro"
cask "slack"
cask "sonos"
cask "spotify"
cask "sublime-merge"
cask "transmission"
cask "utm"
cask "visual-studio-code"

mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
